version: '3.9'

services:
  db:
    image: mongo:6.0
    container_name: blackwill_db
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: django_app
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  mongo_data: